import { describe, expect, it } from 'vitest';
import { createCareerState, generateStartingPlayerProfile, type CreatorInput } from '../playerCreator';
import { advanceActiveEvent, applyEventResolution } from './applyEventResolution';
import { forceTierForTest, resolveEventChoice, testTier } from './resolveEventChoice';
import { generateAcademyRival, initializeAcademyArc, RIVAL_ID, WEEK_COMPLETED_FACT_ID } from './academyArc';
import { getEventDefinition } from './eventRegistry';
const input: CreatorInput = { firstName:'Jan', lastName:'Testowy', nationality:'PL', age:16, dominantFoot:'right', customSeed:'', position:'winger', heightCm:174, weightKg:68, seed: 'arc-seed' };
const career = (seed='arc-seed', position: CreatorInput['position']='winger') => initializeAcademyArc(createCareerState(generateStartingPlayerProfile({...input, position}, seed, 0), seed));
const choose = (c: ReturnType<typeof career>, id: string) => applyEventResolution(c, resolveEventChoice(c, getEventDefinition(c.activeEvent!.definitionId).decisions.find(d=>d.id===id)!));
describe('academy arc', () => {
 it('generates deterministic rival and does not duplicate it',()=>{ const a=career('same'); const b=career('same'); expect(generateAcademyRival(a)).toEqual(generateAcademyRival(b)); expect(initializeAcademyArc(a).significantPeople.filter(p=>p.id===RIVAL_ID)).toHaveLength(1); });
 it('resolves same decision deterministically and links facts to causes',()=>{ let a=choose(career('det'),'declare_senior_ambition'); const b=choose(career('det'),'declare_senior_ambition'); expect(a.activeEvent!.result).toEqual(b.activeEvent!.result); a=advanceActiveEvent(a); a=choose(a,'take_action'); expect(a.historyFacts.at(-1)?.causes).toContain('fact_academy_coach_introduction_declare_senior_ambition'); });
 it('can produce different tiers for different seeds and exposes all tier mapping',()=>{ const seen = new Set(Array.from({length:60},(_,i)=>testTier(career(`s${i}`), career(`s${i}`).activeEvent!, 'take_action', ['technique','pace','finishing']))); expect(seen.size).toBeGreaterThan(1); expect([30,45,60,70,90].map(forceTierForTest)).toEqual(['criticalFailure','failure','mixed','success','criticalSuccess']); });
 it('updates coach and rival relationships, threads, fails forward, completes without restart',()=>{ let c=choose(career('full'),'ask_team_needs'); expect(c.relationships.person_marek_wrona!.trust).toBeGreaterThan(50); expect(c.storyThreads.some(t=>t.id==='coach_trust_thread')).toBe(true); c=advanceActiveEvent(c); c=choose(c,'play_rival'); expect(c.relationships[RIVAL_ID]!.gratitude).toBeGreaterThan(0); c=advanceActiveEvent(c); c=choose(c,'share_credit'); c=advanceActiveEvent(c); expect(c.historyFacts.some(f=>f.id===WEEK_COMPLETED_FACT_ID)).toBe(true); expect(initializeAcademyArc(c).activeEvent).toBeUndefined(); });
 it('uses goalkeeper-specific choices and prevents double resolution',()=>{ const c=career('gk','goalkeeper'); const choices=getEventDefinition('academy_first_scrimmage').decisions.filter(d=>d.id.startsWith('gk_')); expect(choices.map(c=>c.id)).toContain('gk_safe'); let n=advanceActiveEvent(choose(c,'humble_learning')); n=choose(n,'gk_safe'); const twice=applyEventResolution(n, resolveEventChoice(n, choices[2]!)); expect(twice.historyFacts).toHaveLength(n.historyFacts.length); });
});
