import type { EventDefinition } from '../../types/domain';

const choice = (id: string) => ({ id, labelKey: `events.academy.${id}.label`, descriptionKey: `events.academy.${id}.description`, visiblePros: [`events.academy.${id}.pros`], visibleCons: [`events.academy.${id}.cons`] });
export const academyEventDefinitions: EventDefinition[] = [
  { id: 'academy_coach_introduction', version: 1, category: 'academy', tags: ['academy_first_week','coach_first_impression'], availabilityConditions: [], cast: ['coach'], playerInformationKeys: ['events.academy.coach_intro.info'], decisions: [choice('ask_team_needs'), choice('declare_senior_ambition'), choice('humble_learning')], hiddenTests: [], consequences: [], nextEventIds: ['academy_first_scrimmage'], localizationKeys: { title: 'events.academy.coach_intro.title', summary: 'events.academy.coach_intro.summary' } },
  { id: 'academy_first_scrimmage', version: 1, category: 'academy', tags: ['academy_first_week','first_scrimmage'], availabilityConditions: [], cast: ['coach','rival'], playerInformationKeys: ['events.academy.scrimmage.info'], decisions: [choice('take_action'), choice('play_rival'), choice('organize_team'), choice('gk_long_counter'), choice('gk_short_shape'), choice('gk_safe')], hiddenTests: [{ id: 'scrimmage', attribute: 'composure', difficulty: 62 }], consequences: [], nextEventIds: ['academy_rival_reaction'], localizationKeys: { title: 'events.academy.scrimmage.title', summary: 'events.academy.scrimmage.summary' } },
  { id: 'academy_rival_reaction', version: 1, category: 'academy', tags: ['academy_first_week','first_rival'], availabilityConditions: [], cast: ['rival'], playerInformationKeys: ['events.academy.rival.info'], decisions: [choice('share_credit'), choice('stress_rivalry'), choice('dismiss_reaction')], hiddenTests: [], consequences: [], nextEventIds: ['academy_first_week_summary'], localizationKeys: { title: 'events.academy.rival.title', summary: 'events.academy.rival.summary' } },

  { id: 'academy_week_two_feedback', version: 1, category: 'academy', tags: ['academy_second_week','academy_feedback'], availabilityConditions: ['academy_first_week_completed'], cast: ['coach'], playerInformationKeys: ['events.academy.week2.feedback.info'], decisions: [choice('sharpen_strength'), choice('address_weakness'), choice('protect_readiness')], hiddenTests: [], consequences: [], nextEventIds: ['academy_rival_extra_session'], localizationKeys: { title: 'events.academy.week2.feedback.title', summary: 'events.academy.week2.feedback.summary' } },
  { id: 'academy_rival_extra_session', version: 1, category: 'academy', tags: ['academy_second_week','rival_preparation'], availabilityConditions: [], cast: ['rival'], playerInformationKeys: ['events.academy.week2.rival.info'], decisions: [choice('train_together'), choice('turn_into_duel'), choice('choose_recovery')], hiddenTests: [], consequences: [], nextEventIds: ['academy_final_assessment'], localizationKeys: { title: 'events.academy.week2.rival.title', summary: 'events.academy.week2.rival.summary' } },
  { id: 'academy_final_assessment', version: 1, category: 'academy', tags: ['academy_second_week','final_assessment'], availabilityConditions: [], cast: ['coach','rival'], playerInformationKeys: ['events.academy.week2.assessment.info'], decisions: [choice('assessment_use_strength'), choice('assessment_follow_plan'), choice('assessment_adapt'), choice('gk_assessment_use_strength'), choice('gk_assessment_follow_plan'), choice('gk_assessment_adapt')], hiddenTests: [{ id: 'final_assessment', attribute: 'composure', difficulty: 66 }], consequences: [], nextEventIds: ['academy_selection_announcement'], localizationKeys: { title: 'events.academy.week2.assessment.title', summary: 'events.academy.week2.assessment.summary' } },
  { id: 'academy_selection_announcement', version: 1, category: 'academy', tags: ['academy_second_week','senior_trial_decision'], availabilityConditions: [], cast: ['coach','rival'], playerInformationKeys: ['events.academy.week2.selection.info'], decisions: [choice('hear_selection_decision')], hiddenTests: [], consequences: [], nextEventIds: ['academy_selection_response'], localizationKeys: { title: 'events.academy.week2.selection.title', summary: 'events.academy.week2.selection.summary' } },
  { id: 'academy_selection_response', version: 1, category: 'academy', tags: ['academy_second_week','coach_selection_response'], availabilityConditions: [], cast: ['coach'], playerInformationKeys: ['events.academy.week2.response.info'], decisions: [choice('respond_seek_expectations'), choice('respond_stay_grounded'), choice('respond_acknowledge_rival'), choice('respond_request_plan'), choice('respond_return_to_work'), choice('respond_challenge_decision')], hiddenTests: [], consequences: [], nextEventIds: ['academy_second_week_summary'], localizationKeys: { title: 'events.academy.week2.response.title', summary: 'events.academy.week2.response.summary' } },
  { id: 'academy_second_week_summary', version: 1, category: 'academy', tags: ['academy_second_week'], availabilityConditions: [], cast: ['coach','rival'], playerInformationKeys: [], decisions: [choice('close_second_week')], hiddenTests: [], consequences: [], nextEventIds: [], localizationKeys: { title: 'events.academy.week2.summary.title', summary: 'events.academy.week2.summary.summary' } },
  { id: 'academy_first_week_summary', version: 1, category: 'academy', tags: ['academy_first_week'], availabilityConditions: [], cast: ['coach','rival'], playerInformationKeys: [], decisions: [], hiddenTests: [], consequences: [], nextEventIds: [], localizationKeys: { title: 'events.academy.summary.title', summary: 'events.academy.summary.summary' } },
];
export const getEventDefinition = (id: string) => {
  const definition = academyEventDefinitions.find((event) => event.id === id);
  if (!definition) throw new Error(`Unknown event definition: ${id}`);
  return definition;
};
