import { createCareerState, generateStartingPlayerProfile, type CreatorInput } from '../core/playerCreator';
import { advanceActiveEvent, applyEventResolution } from '../core/events/applyEventResolution';
import { initializeAcademyArc, initializeSecondAcademyWeek } from '../core/events/academyArc';
import { getEventDefinition } from '../core/events/eventRegistry';
import { resolveEventChoice, type ResolutionTier } from '../core/events/resolveEventChoice';
export interface AcademySelectionSimulationReport { outcomes: Record<string, number>; tiers: Record<ResolutionTier, number>; averageFitnessBeforeAssessment: number; strategies: Record<string, Record<string, number>> }
const input = (seed: string): CreatorInput => ({ firstName: 'Jan', lastName: 'Testowy', nationality: 'PL', age: 16, dominantFoot: 'right', customSeed: '', position: 'winger', heightCm: 174, weightKg: 68, seed });
const pick = (eventId: string, decisionId: string) => getEventDefinition(eventId).decisions.find((d) => d.id === decisionId)!
const run = (seed: string, choices: string[]) => { let c = initializeAcademyArc(createCareerState(generateStartingPlayerProfile(input(seed), seed, 0), seed)); for (const id of choices.slice(0,3)) { c = applyEventResolution(c, resolveEventChoice(c, pick(c.activeEvent!.definitionId, id))); c = advanceActiveEvent(c); } c = initializeSecondAcademyWeek(c); c = applyEventResolution(c, resolveEventChoice(c, pick(c.activeEvent!.definitionId, choices[3]!))); c = advanceActiveEvent(c); c = applyEventResolution(c, resolveEventChoice(c, pick(c.activeEvent!.definitionId, choices[4]!))); c = advanceActiveEvent(c); const fitness = c.player.fitness; c = applyEventResolution(c, resolveEventChoice(c, pick(c.activeEvent!.definitionId, choices[5]!))); const tier = c.activeEvent!.result!.tier as ResolutionTier; c = advanceActiveEvent(c); c = applyEventResolution(c, resolveEventChoice(c, pick(c.activeEvent!.definitionId, 'hear_selection_decision'))); const outcome = String(c.historyFacts.find((f) => f.factType === 'academy_selection_result')!.data.selectionOutcome); return { outcome, tier, fitness }; };
export const simulateAcademySelection = (options: { samples?: number } = {}): AcademySelectionSimulationReport => { const samples = options.samples ?? 500; const strategies: Record<string, string[]> = { individualna: ['declare_senior_ambition','take_action','stress_rivalry','sharpen_strength','turn_into_duel','assessment_use_strength'], zespolowa: ['ask_team_needs','play_rival','share_credit','address_weakness','train_together','assessment_follow_plan'], ostrozna: ['humble_learning','organize_team','share_credit','protect_readiness','choose_recovery','assessment_adapt'], konfliktowa: ['declare_senior_ambition','take_action','dismiss_reaction','sharpen_strength','turn_into_duel','assessment_adapt'] }; const outcomes: Record<string, number> = {}; const tiers: Record<ResolutionTier, number> = { criticalFailure:0, failure:0, mixed:0, success:0, criticalSuccess:0 }; const strategyResults: Record<string, Record<string, number>> = {}; let fitnessSum = 0; Object.entries(strategies).forEach(([name, choices]) => { strategyResults[name] = {}; for (let i=0;i<samples;i+=1) { const r=run(`sim-${name}-${i}`, choices); outcomes[r.outcome]=(outcomes[r.outcome]??0)+1; strategyResults[name]![r.outcome]=(strategyResults[name]![r.outcome]??0)+1; tiers[r.tier]+=1; fitnessSum += r.fitness; } }); return { outcomes, tiers, averageFitnessBeforeAssessment: Math.round(fitnessSum / (samples * Object.keys(strategies).length)), strategies: strategyResults }; };
