import { useMemo, useState } from 'react';
import { previewRandomSequence } from '../devtools/randomPreview';
import { validateSampleContent } from '../schemas/validateContent';
import { translate } from '../core/narrative/localization';
import { attributeKeys, canReroll, createCareerState, defaultBodyForPosition, generateStartingPlayerProfile, identityInputSchema, makeReadableSeed, positionIds, profileInputSchema, type IdentityInput, type PositionId, type StartingPlayerProfile } from '../core/playerCreator';
import { hasValidCareer, loadCareer, saveCareer } from '../core/persistence';
import type { CareerState, PlayerAttributes } from '../types/domain';
import './App.css';

const infoKey = 'mfl.localSaveInfoDismissed';
const tabs = [['game','nav.game'],['player','nav.player'],['club','nav.club'],['relationships','nav.relationships'],['history','nav.history'],['devtools','nav.devtools']] as const;

const tParam = (key: string, params: Record<string,string>) => translate(key, Object.fromEntries(Object.entries(params).map(([k,v]) => [k, translate(v)])));
const initials = (first: string, last: string) => `${first[0] ?? 'M'}${last[0] ?? 'F'}`.toUpperCase();

const RadarChart = ({ attributes }: { attributes: PlayerAttributes }) => {
  const center = 105; const max = 75;
  const points = attributeKeys.map((key, index) => { const angle = -Math.PI / 2 + (Math.PI * 2 * index) / attributeKeys.length; const radius = (attributes[key] / 100) * max; return `${center + Math.cos(angle) * radius},${center + Math.sin(angle) * radius}`; }).join(' ');
  return <figure className="radar"><svg viewBox="0 0 210 210" role="img" aria-labelledby="radar-title"><title id="radar-title">Wykres radarowy atrybutów</title>{[.25,.5,.75,1].map((scale) => <circle key={scale} cx={center} cy={center} r={max * scale} fill="none" stroke="rgba(255,255,255,.14)" />)}{attributeKeys.map((key, index) => { const angle = -Math.PI / 2 + (Math.PI * 2 * index) / attributeKeys.length; const x = center + Math.cos(angle) * 92; const y = center + Math.sin(angle) * 92; return <g key={key}><line x1={center} y1={center} x2={center + Math.cos(angle) * max} y2={center + Math.sin(angle) * max} stroke="rgba(255,255,255,.12)"/><text x={x} y={y} textAnchor="middle">{translate(`attribute.${key}`)}</text></g>; })}<polygon points={points} fill="rgba(68, 209, 157, .35)" stroke="#44d19d" strokeWidth="3" /></svg><figcaption>{attributeKeys.map((key) => `${translate(`attribute.${key}`)} ${attributes[key]}`).join(', ')}</figcaption></figure>;
};

const PlayerCard = ({ profile, seed }: { profile: StartingPlayerProfile; seed: string }) => <section className="card"><div className={`portrait portrait-${seed.length % 4}`}><span>{initials(profile.player.firstName, profile.player.lastName)}</span></div><div><h3>{profile.player.firstName} {profile.player.lastName}</h3><p>{profile.player.age} lat · {translate(`nationality.${profile.player.nationality}`)} · {translate(`position.${profile.player.primaryPosition}`)}</p><p>{profile.player.heightCm} cm · {profile.player.weightKg} kg · {translate(profile.player.traits[0] === 'foot_left' ? 'foot.left' : 'foot.right')}</p><p>{tParam(profile.profileDescriptionKey, profile.profileDescriptionParams)}</p><p><strong>Seed kariery:</strong> <code>{seed}</code></p><p><strong>Pierwszy klub:</strong> Vistula Nova</p></div><RadarChart attributes={profile.player.attributes}/><ul className="attrs">{attributeKeys.map((key) => <li key={key}><span>{translate(`attribute.${key}`)}</span><strong>{profile.player.attributes[key]}</strong></li>)}</ul></section>;

export const App = () => {
  const [view, setView] = useState<'start'|'creator'|'career'>(() => hasValidCareer() ? 'start' : 'start');
  const [career, setCareer] = useState<CareerState | null>(() => { const loaded = loadCareer(); return loaded.ok ? loaded.save.career : null; });
  const [step, setStep] = useState(0); const [roll, setRoll] = useState(0); const [active, setActive] = useState<(typeof tabs)[number][0]>('game');
  const [identity, setIdentity] = useState<IdentityInput>({ firstName: '', lastName: '', nationality: 'PL', age: 17, dominantFoot: 'right', customSeed: '' });
  const [profileInput, setProfileInput] = useState<{ position: PositionId; heightCm: number; weightKg: number }>({ position: 'winger', heightCm: 174, weightKg: 68 });
  const [seed, setSeed] = useState(''); const [errors, setErrors] = useState<string[]>([]); const [showInfo, setShowInfo] = useState(() => localStorage.getItem(infoKey) !== '1');
  const generated = useMemo(() => seed ? generateStartingPlayerProfile({ ...identity, ...profileInput, seed }, seed, roll) : null, [identity, profileInput, seed, roll]);
  const validation = useMemo(() => validateSampleContent(), []); const randomPreview = useMemo(() => previewRandomSequence(`mfl-sample-career-2026:${roll}`), [roll]);

  const startNew = () => { if (career && !confirm(translate('start.confirmOverwrite'))) return; setView('creator'); setStep(0); setRoll(0); setSeed(''); };
  const continueCareer = () => { const loaded = loadCareer(); if (loaded.ok) { setCareer(loaded.save.career); setView('career'); } };
  const nextIdentity = () => { const result = identityInputSchema.safeParse(identity); if (!result.success) { setErrors(result.error.issues.map((i) => i.message)); return; } setErrors([]); setSeed(result.data.customSeed?.trim() || makeReadableSeed()); setStep(1); };
  const nextProfile = () => { const result = profileInputSchema.safeParse(profileInput); if (!result.success) { setErrors(result.error.issues.map((i) => i.message)); return; } setErrors([]); setStep(2); };
  const finish = () => { if (!generated) return; const next = createCareerState(generated, seed); saveCareer(next); setCareer(next); setView('career'); };

  if (view === 'career' && career) return <main className="shell"><header className="hero"><p>Lipiec 2026 — pierwszy dzień w akademii</p><h1>{translate('app.title')}</h1><span>Rozpoczynasz przygotowania z zespołem młodzieżowym Vistula Nova. Trener zapowiedział, że podczas najbliższych tygodni zdecyduje, kto otrzyma szansę trenowania z seniorami.</span></header><nav className="tabs">{tabs.map(([id,label]) => <button key={id} onClick={() => setActive(id)} className={active === id ? 'active' : ''}>{translate(label)}</button>)}</nav><section className="panel">{active === 'devtools' ? <div className="devgrid"><code>{career.seed}</code><pre>{JSON.stringify(randomPreview, null, 2)}</pre><p>OK: {validation.events.length} wydarzenie, {validation.clubs.length} klub, {validation.people.length} postać.</p></div> : <><h2>{translate(active === 'game' ? 'career.firstDay.title' : 'common.inPreparation')}</h2><p>{translate('career.nextStage')}</p><div className="career-grid"><PlayerCard profile={{ player: career.player, profileDescriptionKey: 'creator.profileDescription', profileDescriptionParams: { strong1: 'attribute.technique', strong2: 'attribute.vision', weak: 'attribute.defending', position: `position.${career.player.primaryPosition}` }, rollIndex: 0 }} seed={career.seed}/><aside><p><strong>Klub:</strong> {career.currentClub.name}</p><p><strong>Pozycja:</strong> {translate(`position.${career.player.primaryPosition}`)}</p><p><strong>Morale:</strong> {career.player.morale}</p><p><strong>Kondycja:</strong> {career.player.fitness}</p><h3>Pierwszy wpis historii</h3><p>{translate('history.careerStarted')}</p></aside></div></>}</section></main>;

  if (view === 'creator') return <main className="shell narrow"><header className="hero"><p>Nowa kariera</p><h1>Kreator zawodnika</h1></header><ol className="steps">{['Tożsamość','Profil','Atrybuty','Podsumowanie'].map((label, i) => <li className={i === step ? 'active' : ''} key={label}>{label}</li>)}</ol>{errors.length > 0 && <div className="errors">{errors.map((e) => <p key={e}>{e}</p>)}</div>}<section className="panel">{step === 0 && <div className="form"><input placeholder="Imię" value={identity.firstName} onChange={(e) => setIdentity({...identity, firstName: e.target.value})}/><input placeholder="Nazwisko" value={identity.lastName} onChange={(e) => setIdentity({...identity, lastName: e.target.value})}/><select value={identity.nationality} onChange={(e) => setIdentity({...identity, nationality: e.target.value as IdentityInput['nationality']})}><option value="PL">Polska</option></select><input type="number" min="16" max="18" value={identity.age} onChange={(e) => setIdentity({...identity, age: Number(e.target.value)})}/><select value={identity.dominantFoot} onChange={(e) => setIdentity({...identity, dominantFoot: e.target.value as IdentityInput['dominantFoot']})}><option value="right">Prawa noga</option><option value="left">Lewa noga</option></select><input placeholder="Opcjonalny własny seed" value={identity.customSeed} onChange={(e) => setIdentity({...identity, customSeed: e.target.value})}/><button onClick={nextIdentity}>Dalej</button></div>}{step === 1 && <div className="form"><div className="positions">{positionIds.map((id) => <button className={profileInput.position === id ? 'active' : ''} key={id} onClick={() => { const [heightCm, weightKg] = defaultBodyForPosition(id); setProfileInput({ position: id, heightCm, weightKg }); }}><strong>{translate(`position.${id}`)}</strong><span>{translate(`position.${id}.description`)}</span></button>)}</div><input type="number" value={profileInput.heightCm} onChange={(e) => setProfileInput({...profileInput, heightCm: Number(e.target.value)})}/><input type="number" value={profileInput.weightKg} onChange={(e) => setProfileInput({...profileInput, weightKg: Number(e.target.value)})}/><button onClick={() => setStep(0)}>Wstecz</button><button onClick={nextProfile}>Dalej</button></div>}{step === 2 && generated && <><PlayerCard profile={generated} seed={seed}/><p>Pozostałe ponowne losowania: {2 - roll}</p><button disabled={!canReroll(roll)} onClick={() => setRoll((r) => r + 1)}>Losuj ponownie</button><button onClick={() => setStep(3)}>Akceptuj atrybuty</button></>}{step === 3 && generated && <><PlayerCard profile={generated} seed={seed}/><button onClick={() => setStep(1)}>Wróć i popraw</button><button onClick={finish}>Rozpocznij karierę</button></>}</section></main>;

  return <main className="shell start"><header className="hero"><p>{translate('start.subtitle')}</p><h1>{translate('app.title')}</h1></header>{showInfo && <aside className="notice"><p>{translate('start.localSaveNotice')}</p><button onClick={() => { localStorage.setItem(infoKey, '1'); setShowInfo(false); }}>Rozumiem</button></aside>}<section className="panel menu"><button onClick={startNew}>Nowa kariera</button><button disabled={!career} onClick={continueCareer}>Kontynuuj</button><a href="https://github.com/adamfron/my_football_legend">O projekcie</a><button className="subtle" onClick={() => setView('career')}>Narzędzia developerskie</button></section></main>;
};
