import type { CareerState, EventDecision, EventInstance, HistoryFact, PlayerAttributes, RelationshipScores } from '../../../types/domain';
import { COACH_ID, RIVAL_ID } from '../academyArc';
import { RandomGenerator } from '../../random/RandomGenerator';
import type { EventResolution, ResolutionTier } from '../resolveEventChoice';

export type SelectionOutcome = 'player_invited' | 'both_invited' | 'rival_invited_player_plan' | 'extended_assessment';
export interface AcademyCandidateEvaluation { sportingAssessment: number; tacticalAssessment: number; coachConfidence: number; readiness: number; narrativeFlags: string[] }
export interface RivalAcademyProfile { baselineQuality: number; readiness: number; tacticalFit: number; pressureResponse: number }

const tiers: ResolutionTier[] = ['criticalFailure', 'failure', 'mixed', 'success', 'criticalSuccess'];
const clampScore = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
const average = (attrs: PlayerAttributes, keys: (keyof PlayerAttributes)[]) => keys.reduce((sum, key) => sum + attrs[key], 0) / keys.length;
const tierFor = (score: number): ResolutionTier => score < 42 ? 'criticalFailure' : score < 54 ? 'failure' : score < 66 ? 'mixed' : score < 82 ? 'success' : 'criticalSuccess';
const group = (position: string) => position === 'goalkeeper' ? 'goalkeeper' : ['center_back', 'full_back'].includes(position) ? 'defender' : ['defensive_midfielder', 'central_midfielder', 'attacking_midfielder'].includes(position) ? 'midfielder' : 'forward';
const roleAttrs = (position: string): (keyof PlayerAttributes)[] => group(position) === 'goalkeeper' ? ['composure', 'vision', 'leadership'] : group(position) === 'defender' ? ['defending', 'composure', 'leadership'] : group(position) === 'midfielder' ? ['vision', 'technique', 'composure'] : ['finishing', 'pace', 'technique'];
export const attributeName = (key: keyof PlayerAttributes) => ({ technique: 'technika', vision: 'czytanie gry', pace: 'tempo', stamina: 'wytrzymałość', finishing: 'wykończenie', defending: 'obrona', leadership: 'przywództwo', composure: 'opanowanie', spatialAwareness: 'orientacja przestrzenna', determination: 'determinacja', ambition: 'ambicja', professionalism: 'profesjonalizm' } satisfies Record<keyof PlayerAttributes, string>)[key];
export const selectAcademyFeedbackAttributes = (career: CareerState) => {
  const entries = Object.entries(career.player.attributes) as [keyof PlayerAttributes, number][];
  const preferred = roleAttrs(career.player.primaryPosition);
  const strong = [...entries].sort((a, b) => (preferred.includes(b[0]) ? 8 : 0) + b[1] - ((preferred.includes(a[0]) ? 8 : 0) + a[1]))[0]![0];
  const first = career.historyFacts.find((f) => f.factType === 'academy_training_result');
  const needBias: Partial<Record<keyof PlayerAttributes, number>> = first?.data.decisionId === 'take_action' ? { vision: -8, composure: -6 } : first?.data.decisionId === 'play_rival' ? { finishing: -5, pace: -4 } : { technique: -4, pace: -3 };
  const weak = [...entries].sort((a, b) => (a[1] + (preferred.includes(a[0]) ? -7 : 5) + (needBias[a[0]] ?? 0)) - (b[1] + (preferred.includes(b[0]) ? -7 : 5) + (needBias[b[0]] ?? 0)))[0]![0];
  return { strongAttribute: strong, developmentAttribute: weak };
};
const mkFact = (career: CareerState, event: EventInstance, decision: EventDecision, factType: string, data: Record<string, unknown>, tier: ResolutionTier = 'success', targets = [COACH_ID], importance = 65): HistoryFact => ({ id: `fact_${event.definitionId}_${decision.id}`, factType, season: career.currentSeason, date: String(event.context.date), actors: [career.player.id], targets, clubs: [career.currentClub.id], competitions: [], data: { decisionId: decision.id, ...data, resolutionTier: tier }, causes: career.historyFacts.filter((f) => f.factType.startsWith('academy_')).map((f) => f.id), tags: ['academy_second_week', factType, ...(factType.includes('selection') ? ['senior_trial_decision'] : []), ...(factType.includes('assessment') ? ['final_assessment'] : []), ...(factType.includes('training_focus') ? ['academy_feedback'] : [])], visibility: 'partial', narrativeImportance: importance, emotionalTone: tier.includes('Failure') ? 'negative' : tier === 'mixed' ? 'bittersweet' : 'positive' });
export const resolveWeekTwoFeedback = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => {
  const attrs = selectAcademyFeedbackAttributes(career);
  const focusType = decision.id === 'sharpen_strength' ? 'individual_edge' : decision.id === 'address_weakness' ? 'coach_instruction' : 'readiness';
  const rel: Partial<RelationshipScores> = decision.id === 'address_weakness' ? { trust: 5, professionalDependence: 3 } : decision.id === 'sharpen_strength' ? { respect: 3 } : { trust: 2, respect: 2 };
  const data = { ...attrs, targetAttribute: attrs.developmentAttribute, focusType, strongAttributeName: attributeName(attrs.strongAttribute), developmentAttributeName: attributeName(attrs.developmentAttribute), visibleConsequences: decision.visiblePros };
  return { tier: 'success', objectiveOutcome: decision.id, moraleDelta: decision.id === 'sharpen_strength' ? 2 : 0, fitnessDelta: decision.id === 'protect_readiness' ? 6 : decision.id === 'sharpen_strength' ? -5 : -2, reputationDelta: 0, relationshipChanges: { [COACH_ID]: rel }, interpretations: [{ observerId: COACH_ID, frame: decision.id === 'protect_readiness' ? 'cautious' : 'mature', relationshipChanges: rel, public: false }], fact: mkFact(career, event, decision, 'academy_training_focus', data), nextEventId: 'academy_rival_extra_session' };
};
export const resolveRivalExtraSession = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => {
  const rel = decision.id === 'train_together' ? { trust: 7, gratitude: 6, liking: 3 } : decision.id === 'turn_into_duel' ? { respect: 7, rivalry: 8, resentment: 2 } : { trust: -2, rivalry: 2 };
  const data = { preparationType: decision.id, relationshipContext: event.context.relationshipContext ?? 'neutral' };
  return { tier: 'success', objectiveOutcome: decision.id, moraleDelta: decision.id === 'turn_into_duel' ? 2 : 0, fitnessDelta: decision.id === 'choose_recovery' ? 7 : decision.id === 'turn_into_duel' ? -8 : -5, reputationDelta: decision.id === 'turn_into_duel' ? 2 : 0, relationshipChanges: { [RIVAL_ID]: rel }, interpretations: [{ observerId: RIVAL_ID, frame: decision.id === 'turn_into_duel' ? 'ambitious' : decision.id === 'choose_recovery' ? 'cautious' : 'team_oriented', relationshipChanges: rel, public: false }], fact: mkFact(career, event, decision, 'academy_rival_preparation', data, 'success', [RIVAL_ID]), nextEventId: 'academy_final_assessment' };
};
export const buildRivalAcademyProfile = (career: CareerState): RivalAcademyProfile => { const rng = RandomGenerator.fromSeed(`${career.seed}:rival:selection`); const rel = career.relationships[RIVAL_ID]; const prep = career.historyFacts.find((f) => f.factType === 'academy_rival_preparation')?.data.decisionId; return { baselineQuality: rng.int(48, 76), readiness: clampScore(rng.int(48, 72) + (prep === 'train_together' ? 6 : prep === 'turn_into_duel' ? -2 : 3)), tacticalFit: rng.int(45, 75) + (rel?.trust ?? 50) / 20, pressureResponse: rng.int(44, 78) + (rel?.rivalry ?? 20) / 15 }; };
export const evaluateAcademyCandidate = (career: CareerState, assessmentResolution: { decisionId: string; tier: ResolutionTier }): AcademyCandidateEvaluation => {
  const attrs = career.player.attributes; const focus = career.historyFacts.find((f) => f.factType === 'academy_training_focus')?.data.decisionId; const rivalPrep = career.historyFacts.find((f) => f.factType === 'academy_rival_preparation')?.data.decisionId; const first = career.historyFacts.find((f) => f.factType === 'academy_training_result'); const coach = career.relationships[COACH_ID]; const rival = career.relationships[RIVAL_ID]; const rng = RandomGenerator.fromSeed(`${career.seed}:academy-final:${assessmentResolution.decisionId}`);
  const strength = average(attrs, roleAttrs(career.player.primaryPosition)); const tactical = average(attrs, ['vision', 'composure', group(career.player.primaryPosition) === 'defender' ? 'defending' : 'leadership']); const firstBoost = tiers.indexOf(String(first?.data.resolutionTier) as ResolutionTier) - 2;
  return { sportingAssessment: clampScore(strength + firstBoost * 4 + (focus === 'sharpen_strength' ? 7 : 0) + (assessmentResolution.decisionId === 'assessment_use_strength' ? 5 : 0) + rng.int(-12, 12)), tacticalAssessment: clampScore(tactical + (focus === 'address_weakness' ? 8 : 0) + (assessmentResolution.decisionId === 'assessment_follow_plan' ? 5 : assessmentResolution.decisionId === 'assessment_adapt' ? 4 : -2)), coachConfidence: clampScore(((coach?.trust ?? 50) + (coach?.respect ?? 50)) / 2 + (focus === 'address_weakness' ? 6 : 0) + firstBoost * 3), readiness: clampScore(career.player.fitness + (focus === 'protect_readiness' ? 8 : 0) + (rivalPrep === 'turn_into_duel' ? -4 : 0)), narrativeFlags: [focus === 'protect_readiness' ? 'fresh' : 'loaded', (rival?.trust ?? 50) > 60 ? 'rival_cooperation' : (rival?.rivalry ?? 20) > 55 ? 'rival_pressure' : 'rival_neutral'] };
};
export const resolveFinalAssessment = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => {
  const attrs = decision.id === 'assessment_use_strength' ? roleAttrs(career.player.primaryPosition).slice(0, 2) : decision.id === 'assessment_follow_plan' ? ['composure', roleAttrs(career.player.primaryPosition)[0]!] : ['vision', career.player.attributes.leadership >= career.player.attributes.composure ? 'leadership' : 'composure'];
  const rng = RandomGenerator.import(event.randomState).fork(decision.id); const base = average(career.player.attributes, attrs as (keyof PlayerAttributes)[]) + (career.player.morale - 50) * 0.12 + (career.player.fitness - 50) * 0.15 + rng.int(-18, 18);
  const tier = tierFor(base); const evaluation = evaluateAcademyCandidate(career, { decisionId: decision.id, tier }); const rivalProfile = buildRivalAcademyProfile(career);
  return { tier, objectiveOutcome: `${decision.id}_${tier}`, moraleDelta: tiers.indexOf(tier) >= 3 ? 4 : tiers.indexOf(tier) <= 1 ? -3 : 0, fitnessDelta: -6, reputationDelta: tiers.indexOf(tier) >= 3 ? 3 : 0, relationshipChanges: { [COACH_ID]: { respect: tiers.indexOf(tier) - 2, trust: decision.id === 'assessment_follow_plan' ? 3 : 0 } }, interpretations: [{ observerId: COACH_ID, frame: decision.id === 'assessment_adapt' ? 'brave' : 'mature', relationshipChanges: {}, public: false }], fact: mkFact(career, event, decision, 'academy_final_assessment', { evaluation, rivalProfile }, tier, [COACH_ID, RIVAL_ID], 82), nextEventId: 'academy_selection_announcement' };
};
export const chooseSelectionOutcome = (career: CareerState): SelectionOutcome => { const final = career.historyFacts.find((f) => f.factType === 'academy_final_assessment'); const e = final?.data.evaluation as AcademyCandidateEvaluation | undefined; const r = final?.data.rivalProfile as RivalAcademyProfile | undefined; const player = ((e?.sportingAssessment ?? 55) + (e?.tacticalAssessment ?? 55) + (e?.coachConfidence ?? 50) + (e?.readiness ?? 50)) / 4; const rival = ((r?.baselineQuality ?? 55) + (r?.readiness ?? 55) + (r?.tacticalFit ?? 55) + (r?.pressureResponse ?? 55)) / 4; if (player >= 67 && rival >= 65) return 'both_invited'; if (player >= rival + 3 || player >= 70) return 'player_invited'; if (rival >= player + 8 && player < 63) return 'rival_invited_player_plan'; return 'extended_assessment'; };
export const resolveSelectionAnnouncement = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => {
  const outcome = chooseSelectionOutcome(career); const playerInvited = outcome === 'player_invited' || outcome === 'both_invited'; const rel = playerInvited ? { trust: 4, respect: 4 } : { professionalDependence: 5, trust: 2 };
  return { tier: 'success', objectiveOutcome: outcome, moraleDelta: playerInvited ? 7 : -2, fitnessDelta: 0, reputationDelta: playerInvited ? 5 : 1, relationshipChanges: { [COACH_ID]: rel }, interpretations: [{ observerId: COACH_ID, frame: 'mature', relationshipChanges: rel, public: false }], fact: mkFact(career, event, decision, 'academy_selection_result', { selectionOutcome: outcome, playerAssessmentTags: (career.historyFacts.find((f) => f.factType === 'academy_final_assessment')?.data.evaluation as AcademyCandidateEvaluation | undefined)?.narrativeFlags ?? [], rivalAssessmentTags: ['stabilny konkurent'], reasons: ['dwa tygodnie pracy', 'reakcja w sprawdzianie'], linkedFacts: career.historyFacts.map((f) => f.id) }, 'success', outcome.includes('rival') || outcome === 'both_invited' ? [COACH_ID, RIVAL_ID] : [COACH_ID], 95), nextEventId: 'academy_selection_response' };
};
export const resolveSelectionResponse = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => { const outcome = career.historyFacts.find((f) => f.factType === 'academy_selection_result')?.data.selectionOutcome as SelectionOutcome; const invited = outcome === 'player_invited' || outcome === 'both_invited'; const rel = decision.id === 'respond_challenge_decision' ? { respect: 3, trust: -4 } : decision.id === 'respond_request_plan' || decision.id === 'respond_seek_expectations' ? { trust: 5, professionalDependence: 4 } : { trust: 2 }; return { tier: 'success', objectiveOutcome: decision.id, moraleDelta: invited ? 1 : decision.id === 'respond_challenge_decision' ? 2 : 0, fitnessDelta: 0, reputationDelta: decision.id === 'respond_challenge_decision' ? 2 : 1, relationshipChanges: { [COACH_ID]: rel, ...(decision.id === 'respond_acknowledge_rival' ? { [RIVAL_ID]: { trust: 3, respect: 2 } } : {}) }, interpretations: [{ observerId: COACH_ID, frame: decision.id === 'respond_challenge_decision' ? 'ambitious' : 'mature', relationshipChanges: rel, public: false }], fact: mkFact(career, event, decision, 'academy_selection_response', { selectionOutcome: outcome, invited }, 'success', [COACH_ID], 78), nextEventId: 'academy_second_week_summary' }; };
export const resolveSecondWeekSummary = (career: CareerState, event: EventInstance, decision: EventDecision): EventResolution => ({ tier: 'success', objectiveOutcome: 'academy_second_week_completed', moraleDelta: 0, fitnessDelta: 0, reputationDelta: 0, relationshipChanges: {}, interpretations: [], fact: mkFact(career, event, decision, 'academy_second_week_completed', { nextStage: career.historyFacts.find((f) => f.factType === 'academy_selection_result')?.data.selectionOutcome }, 'success', [COACH_ID, RIVAL_ID], 100) });
